Repository clockworklabs/com.clockworklabs.spacetimedbsdk, pull requests merged in 2024-03, with the labels that each got.

#18 Committing Phoebe's remove row PK changes
  Scripts/ClientApi.cs
  Scripts/ClientCache.cs
  Scripts/SpacetimeDBClient.cs
Labels: abi-break

#27 Committing Phoebe's remove row PK changes
  Scripts/ClientApi.cs
  Scripts/ClientCache.cs
  Scripts/SpacetimeDBClient.cs
Labels: release-alpha

#26 Brotli decompress incoming Websocket messages
  Scripts/SpacetimeDBClient.cs
Labels: abi-break, release-alpha, websocket-compression
