Repository clockworklabs/com.clockworklabs.spacetimedbsdk, pull requests merged in 2024-10, with the labels that each got.

#131 c# client SDK (DbConnection + SDK Callbacks)
  SpacetimeDB.ClientSDK.csproj
  examples~/quickstart/client/Program.cs
  examples~/quickstart/client/module_bindings/Message.cs
  examples~/quickstart/client/module_bindings/SendMessageReducer.cs
  examples~/quickstart/client/module_bindings/SetNameReducer.cs
  examples~/quickstart/client/module_bindings/User.cs
  examples~/quickstart/client/module_bindings/_Globals/SpacetimeDBClient.cs
  examples~/quickstart/server/src/lib.rs
  src/ClientCache.cs
  src/Event.cs
  src/Event.cs.meta
  src/IDatabaseTable.cs
  src/SpacetimeDBClient.cs
  src/Stubs.cs
  src/Stubs.cs.meta
  src/Table.cs
  src/Table.cs.meta
  tests~/SnapshotTests.VerifyAllTablesParsed.verified.txt
  tests~/SnapshotTests.cs
  tests~/VerifyInit.cs
Labels: api-break

#137 Subscription API
  examples~/quickstart/client/Program.cs
  examples~/quickstart/client/module_bindings/_Globals/SpacetimeDBClient.cs
  src/Event.cs
  src/SpacetimeDBClient.cs
  tests~/SnapshotTests.cs
Labels: release-0.12

#139 Merge table cache into table handle
  src/ClientCache.cs
  src/SpacetimeDBClient.cs
  src/Table.cs
Labels: release-0.12

#140 Hide more APIs
  examples~/quickstart/client/Program.cs
  src/ClientCache.cs
  src/ConsoleLogger.cs
  src/SpacetimeDBClient.cs
  src/UnityDebugLogger.cs
  src/WebSocket.cs
  tests~/SnapshotTests.VerifyAllTablesParsed.verified.txt
  tests~/SnapshotTests.cs
  tests~/tests.csproj
Labels: release-0.12

#143 Fix UnityDebugLogger implementation
  src/UnityDebugLogger.cs
Labels: release-0.12

#145 Reduce public API surface further
  src/BSATNHelpers.cs
  src/ISpacetimeDBLogger.cs
  src/SpacetimeDBClient.cs
  src/Stats.cs
Labels: release-0.12

#154 Jeremie/remove break
  src/SpacetimeDBClient.cs
Labels: release-0.12

#152 Update DLLs for 0.12.0
  packages/spacetimedb.bsatn.runtime/0.11.0/analyzers/dotnet/cs/SpacetimeDB.BSATN.Codegen.dll
  packages/spacetimedb.bsatn.runtime/0.11.0/lib/netstandard2.1/SpacetimeDB.BSATN.Runtime.dll
  packages/spacetimedb.bsatn.runtime/0.12.0.meta
  packages/spacetimedb.bsatn.runtime/0.12.0/analyzers.meta
  packages/spacetimedb.bsatn.runtime/0.12.0/analyzers/dotnet.meta
  packages/spacetimedb.bsatn.runtime/0.12.0/analyzers/dotnet/cs.meta
  packages/spacetimedb.bsatn.runtime/0.12.0/analyzers/dotnet/cs/SpacetimeDB.BSATN.Codegen.dll
  packages/spacetimedb.bsatn.runtime/0.12.0/analyzers/dotnet/cs/SpacetimeDB.BSATN.Codegen.dll.meta
  packages/spacetimedb.bsatn.runtime/0.12.0/lib.meta
  packages/spacetimedb.bsatn.runtime/0.12.0/lib/netstandard2.1.meta
  packages/spacetimedb.bsatn.runtime/0.12.0/lib/netstandard2.1/SpacetimeDB.BSATN.Runtime.dll
  packages/spacetimedb.bsatn.runtime/0.12.0/lib/netstandard2.1/SpacetimeDB.BSATN.Runtime.dll.meta
Labels: release-0.12

#153 Accept multiple queries in Subscribe
  src/Event.cs
  src/SpacetimeDBClient.cs
Labels: release-0.12

#141 Fix UnityNetworkManager
  examples~/quickstart/client/module_bindings/_Globals/UnityNetworkManager.cs
  src/SpacetimeDB/ClientApi/BsatnRowList.cs.meta
  src/SpacetimeDB/ClientApi/CompressableQueryUpdate.cs.meta
  src/SpacetimeDB/ClientApi/QueryUpdate.cs.meta
  src/SpacetimeDB/ClientApi/RowSizeHint.cs.meta
  src/SpacetimeDBClient.cs
  src/SpacetimeDBNetworkManager.cs
  src/SpacetimeDBNetworkManager.cs.meta
Labels: release-0.12

#157 Use SpacetimeDBNetworkManager everywhere
  README.md
  src/SpacetimeDBClient.cs
  src/SpacetimeDBNetworkManager.cs
Labels: release-0.12

#166 Fix Connection Error: Success
  examples~/quickstart/client/Program.cs
  src/SpacetimeDBClient.cs
  src/WebSocket.cs
Labels: release-rc1
